version: '3.9'

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: erp-postgres-test
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test
      POSTGRES_DB: erp_test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
  
  redis-test:
    image: redis:7-alpine
    container_name: erp-redis-test
    ports:
      - "6380:6379"
  
  nats-test:
    image: nats:latest
    container_name: erp-nats-test
    command: "-js"
    ports:
      - "4223:4222"
      - "8223:8222"
